### ISSUE TITLE
compile fails

### ISSUE THREAD

**Issue by sunilguptasg** [Madek1/time_picker_plus#1]
[/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/time_picker_plus-0.1.1/lib/time_picker_plus.dart:2200:11](): Error: No named parameter with the name 'autovalidate'.
          autovalidate: _autoValidate,
          ^^^^^^^^^^^^
[/Applications/flutter/packages/flutter/lib/src/widgets/form.dart:40:9](): Context: Found this candidate, but the arguments don't match.

  const Form({
        ^^^^
Failed to compile application.
==========

to test I was using the default counter application with just this change:

void _incrementCounter() async {
    await showTimePickerPlus(
      context: context,
      initialTime: TimeOfDay.now(),
      initialEntryMode: TimePickerPlusEntryMode.dialOnly,
    );
    setState(() async {
      _counter++;
    });
  }

**Comment by Madek1** [comment]
I see, you are not passing a context parameter to the function, what's more, you should use Future<void> type. There can be more mistakes in your code, try to debug them.

Or just use function from [readme](https://github.com/Madek1/time_picker_plus/blob/main/README.md#features) to see how this works

```
Future<TimeOfDay> show(BuildContext context) async {
    final TimeOfDay pickedDate = await showTimePickerPlus(
        context: context,
        initialTime: TimeOfDay.now(),
        initialEntryMode: TimePickerPlusEntryMode.dialOnly,
    );
    return pickedDate;
}
```
I hope this help you.
