### ISSUE TITLE
How do we get into text entry mode?

### ISSUE THREAD

**Issue by sunilguptasg** [Madek1/time_picker_plus#2]
I do not see how this is different from the https://material.io/components/time-pickers/flutter 

I expected that there will be a text entry like "12:25 PM" but do not see it - perhaps I am missing something...

**Comment by Madek1** [comment]
The only difference is that in this widget you have an option to hide "toggle mode option" (icon with keyboard/clock). You can do this using the modes described in [readme](https://github.com/Madek1/time_picker_plus/blob/main/README.md#features)
![image](https://user-images.githubusercontent.com/14925718/153247554-6416faab-241b-4030-a2b3-e8b11cdf2773.png)
